USE ROLE ACCOUNTADMIN;
-- Cheetah -- justine
-- Gecko yn
-- Catfish jn
-- Cat isaac
-- hy ferret

ALTER USER FERRET SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxIAKNi4j846V9m2dOAKWfUsgg+N2XRcNE359BrZfmR/NHjYx0eTd4z5vLyZiHen62JiWUf6KJbwF+pagCB7BXJ4niXvG+RbsmOeyvZwFQXXUrYLHfIoGIjrxpkryVABjyKNnt7qrGOgDLgG06ktdnTjVJ8I+l9x+tDArBPCaTuao50++EfbUx80VL2mgphrzm7oMcdC3Nv4Tx0UJNil4coA/AZB7kYOAhyx0b6zqaEnMcYVnjU2aFQi1A0pog89n1yVeXp/8QgMakWhj6O8MtnFp5DiCZF8KmkoOuL7FgXBozzRgyh/PId1GrWxX7wxZkT62O/34wgnLk7kq/ZB2+QIDAQAB';

-- 1) Create a dedicated read only role for Power BI
CREATE ROLE IF NOT EXISTS POWERBI_READER;

-- 2) Grant database + schema visibility
GRANT USAGE ON DATABASE GRP1_ASG TO ROLE POWERBI_READER;
GRANT USAGE ON SCHEMA GRP1_ASG.ASG_TRANSFORMATIONS TO ROLE POWERBI_READER;

-- 3) Grant read access on existing objects
GRANT SELECT ON ALL TABLES IN SCHEMA GRP1_ASG.ASG_TRANSFORMATIONS TO ROLE POWERBI_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA GRP1_ASG.ASG_TRANSFORMATIONS TO ROLE POWERBI_READER;

-- 4) Grant read access automatically on future objects
GRANT SELECT ON FUTURE TABLES IN SCHEMA GRP1_ASG.ASG_TRANSFORMATIONS TO ROLE POWERBI_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GRP1_ASG.ASG_TRANSFORMATIONS TO ROLE POWERBI_READER;

-- 5) Grant role to all 5 team members
GRANT ROLE POWERBI_READER TO USER CATFISH;
GRANT ROLE POWERBI_READER TO USER CAT;
GRANT ROLE POWERBI_READER TO USER FERRET;
GRANT ROLE POWERBI_READER TO USER GECKO;
GRANT ROLE POWERBI_READER TO USER CHEETAH;

-- 6) Allow each member to use their own warehouse (compute)
GRANT USAGE ON WAREHOUSE CATFISH_WH TO ROLE POWERBI_READER;
GRANT USAGE ON WAREHOUSE CAT_WH TO ROLE POWERBI_READER;
GRANT USAGE ON WAREHOUSE FERRET_WH TO ROLE POWERBI_READER;
GRANT USAGE ON WAREHOUSE GECKO_WH TO ROLE POWERBI_READER;
GRANT USAGE ON WAREHOUSE CHEETAH_WH TO ROLE POWERBI_READER;

-- 7) Optional: set default role only (no default warehouse)
ALTER USER CATFISH SET DEFAULT_ROLE = POWERBI_READER;
ALTER USER CAT SET DEFAULT_ROLE = POWERBI_READER;
ALTER USER FERRET SET DEFAULT_ROLE = POWERBI_READER;
ALTER USER GECKO SET DEFAULT_ROLE = POWERBI_READER;
ALTER USER CHEETAH SET DEFAULT_ROLE = POWERBI_READER;

-- 8) Verification
SHOW GRANTS TO USER CATFISH;
SHOW GRANTS TO USER CAT;
SHOW GRANTS TO USER FERRET;
SHOW GRANTS TO USER GECKO;
SHOW GRANTS TO USER CHEETAH;

-- 9.1) Setting Public Keys for CATFISH
ALTER USER CATFISH SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxIAKNi4j846V9m2dOAKWfUsgg+N2XRcNE359BrZfmR/NHjYx0eTd4z5vLyZiHen62JiWUf6KJbwF+pagCB7BXJ4niXvG+RbsmOeyvZwFQXXUrYLHfIoGIjrxpkryVABjyKNnt7qrGOgDLgG06ktdnTjVJ8I+l9x+tDArBPCaTuao50++EfbUx80VL2mgphrzm7oMcdC3Nv4Tx0UJNil4coA/AZB7kYOAhyx0b6zqaEnMcYVnjU2aFQi1A0pog89n1yVeXp/8QgMakWhj6O8MtnFp5DiCZF8KmkoOuL7FgXBozzRgyh/PId1GrWxX7wxZkT62O/34wgnLk7kq/ZB2+QIDAQAB';

-- 9.2) CAT
ALTER USER CAT SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxIAKNi4j846V9m2dOAKWfUsgg+N2XRcNE359BrZfmR/NHjYx0eTd4z5vLyZiHen62JiWUf6KJbwF+pagCB7BXJ4niXvG+RbsmOeyvZwFQXXUrYLHfIoGIjrxpkryVABjyKNnt7qrGOgDLgG06ktdnTjVJ8I+l9x+tDArBPCaTuao50++EfbUx80VL2mgphrzm7oMcdC3Nv4Tx0UJNil4coA/AZB7kYOAhyx0b6zqaEnMcYVnjU2aFQi1A0pog89n1yVeXp/8QgMakWhj6O8MtnFp5DiCZF8KmkoOuL7FgXBozzRgyh/PId1GrWxX7wxZkT62O/34wgnLk7kq/ZB2+QIDAQAB';

-- 9.3) FERRET
ALTER USER FERRET SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxIAKNi4j846V9m2dOAKWfUsgg+N2XRcNE359BrZfmR/NHjYx0eTd4z5vLyZiHen62JiWUf6KJbwF+pagCB7BXJ4niXvG+RbsmOeyvZwFQXXUrYLHfIoGIjrxpkryVABjyKNnt7qrGOgDLgG06ktdnTjVJ8I+l9x+tDArBPCaTuao50++EfbUx80VL2mgphrzm7oMcdC3Nv4Tx0UJNil4coA/AZB7kYOAhyx0b6zqaEnMcYVnjU2aFQi1A0pog89n1yVeXp/8QgMakWhj6O8MtnFp5DiCZF8KmkoOuL7FgXBozzRgyh/PId1GrWxX7wxZkT62O/34wgnLk7kq/ZB2+QIDAQAB';

-- 9.4) COBRA
ALTER USER GECKO SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxIAKNi4j846V9m2dOAKWfUsgg+N2XRcNE359BrZfmR/NHjYx0eTd4z5vLyZiHen62JiWUf6KJbwF+pagCB7BXJ4niXvG+RbsmOeyvZwFQXXUrYLHfIoGIjrxpkryVABjyKNnt7qrGOgDLgG06ktdnTjVJ8I+l9x+tDArBPCaTuao50++EfbUx80VL2mgphrzm7oMcdC3Nv4Tx0UJNil4coA/AZB7kYOAhyx0b6zqaEnMcYVnjU2aFQi1A0pog89n1yVeXp/8QgMakWhj6O8MtnFp5DiCZF8KmkoOuL7FgXBozzRgyh/PId1GrWxX7wxZkT62O/34wgnLk7kq/ZB2+QIDAQAB';

-- 9.5) CHEETAH
ALTER USER CHEETAH SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxIAKNi4j846V9m2dOAKWfUsgg+N2XRcNE359BrZfmR/NHjYx0eTd4z5vLyZiHen62JiWUf6KJbwF+pagCB7BXJ4niXvG+RbsmOeyvZwFQXXUrYLHfIoGIjrxpkryVABjyKNnt7qrGOgDLgG06ktdnTjVJ8I+l9x+tDArBPCaTuao50++EfbUx80VL2mgphrzm7oMcdC3Nv4Tx0UJNil4coA/AZB7kYOAhyx0b6zqaEnMcYVnjU2aFQi1A0pog89n1yVeXp/8QgMakWhj6O8MtnFp5DiCZF8KmkoOuL7FgXBozzRgyh/PId1GrWxX7wxZkT62O/34wgnLk7kq/ZB2+QIDAQAB';

-- 10) Verification (keys set) 
DESC USER CAT;
DESC USER CATFISH;
DESC USER FERRET;
DESC USER GECKO;
DESC USER CHEETAH;