USE ROLE CICD_ROLE;
USE WAREHOUSE FERRET_WH;
USE DATABASE GRP1_ASG;
USE SCHEMA ASG_TRANSFORMATIONS;


PRINT 'success';
SELECT
  CURRENT_USER()      AS user,
  CURRENT_ROLE()      AS role,
  CURRENT_DATABASE()  AS db,
  CURRENT_SCHEMA()    AS schema,
  CURRENT_WAREHOUSE() AS warehouse;