-- 1) Product inventory profile (stock policy + product hierarchy)
CREATE OR REPLACE TABLE ASG_MART.INVENTORY_PRODUCT_PROFILE AS
SELECT
  p.PRODUCTKEY AS PRODUCT_KEY,
  p.PRODUCTALTERNATEKEY AS PRODUCT_ALTERNATE_KEY,
  COALESCE(NULLIF(TRIM(p.ENGLISHPRODUCTNAME), ''), 'Unknown Product') AS PRODUCT_NAME,
  COALESCE(NULLIF(TRIM(p.COLOR), ''), 'Unknown') AS COLOR,
  COALESCE(NULLIF(TRIM(p.SIZE), ''), 'Unknown') AS SIZE,
  p.WEIGHT AS WEIGHT,
  p.STANDARDCOST AS STANDARD_COST,
  p.LISTPRICE AS LIST_PRICE,
  COALESCE(p.SAFETYSTOCKLEVEL, 0) AS SAFETY_STOCK_LEVEL,
  COALESCE(p.REORDERPOINT, 0) AS REORDER_POINT,
  COALESCE(p.DAYSTOMANUFACTURE, 0) AS DAYS_TO_MANUFACTURE,
  COALESCE(NULLIF(TRIM(p.STATUS), ''), 'Unknown') AS STATUS,
  p.STARTDATE AS START_DATE,
  p.ENDDATE AS END_DATE,
  p.PRODUCTSUBCATEGORYKEY AS PRODUCT_SUBCATEGORY_KEY,
  COALESCE(NULLIF(TRIM(psc.ENGLISHPRODUCTSUBCATEGORYNAME), ''), 'Unknown Subcategory') AS PRODUCT_SUBCATEGORY,
  COALESCE(NULLIF(TRIM(pc.ENGLISHPRODUCTCATEGORYNAME), ''), 'Unknown Category') AS PRODUCT_CATEGORY
FROM ASG_CLEAN.DIMPRODUCT_CLEAN p
LEFT JOIN ASG_CLEAN.DIMPRODUCTSUBCATEGORY_CLEAN psc
  ON p.PRODUCTSUBCATEGORYKEY = psc.PRODUCTSUBCATEGORYKEY
LEFT JOIN ASG_CLEAN.DIMPRODUCTCATEGORY_CLEAN pc
  ON psc.PRODUCTCATEGORYKEY = pc.PRODUCTCATEGORYKEY;

-- 2) Unified order line fact for supply chain analysis
CREATE OR REPLACE TABLE ASG_MART.SUPPLYCHAIN_ORDER_LINE AS
WITH internet AS (
  SELECT
    'Internet' AS SALES_CHANNEL,
    f.SALESORDERNUMBER AS SALES_ORDER_NUMBER,
    f.SALESORDERLINENUMBER AS SALES_ORDER_LINE_NUMBER,
    f.PRODUCTKEY AS PRODUCT_KEY,
    f.CUSTOMERKEY AS CUSTOMER_KEY,
    NULL AS RESELLER_KEY,
    f.SALESTERRITORYKEY AS SALES_TERRITORY_KEY,
    f.ORDERDATE AS ORDER_DATE,
    f.DUEDATE AS DUE_DATE,
    f.SHIPDATE AS SHIP_DATE,
    f.ORDERQUANTITY AS ORDER_QTY,
    CAST(f.SALESAMOUNT AS DECIMAL(18,4)) AS SALES_AMOUNT,
    CAST(f.TOTALPRODUCTCOST AS DECIMAL(18,4)) AS TOTAL_PRODUCT_COST,
    CAST(f.FREIGHT AS DECIMAL(18,4)) AS FREIGHT
  FROM ASG_CLEAN.FACTINTERNETSALES_CLEAN f
),
reseller AS (
  SELECT
    'Reseller' AS SALES_CHANNEL,
    f.SALESORDERNUMBER AS SALES_ORDER_NUMBER,
    f.SALESORDERLINENUMBER AS SALES_ORDER_LINE_NUMBER,
    f.PRODUCTKEY AS PRODUCT_KEY,
    NULL AS CUSTOMER_KEY,
    f.RESELLERKEY AS RESELLER_KEY,
    f.SALESTERRITORYKEY AS SALES_TERRITORY_KEY,
    f.ORDERDATE AS ORDER_DATE,
    f.DUEDATE AS DUE_DATE,
    f.SHIPDATE AS SHIP_DATE,
    f.ORDERQUANTITY AS ORDER_QTY,
    CAST(f.SALESAMOUNT AS DECIMAL(18,4)) AS SALES_AMOUNT,
    CAST(f.TOTALPRODUCTCOST AS DECIMAL(18,4)) AS TOTAL_PRODUCT_COST,
    CAST(f.FREIGHT AS DECIMAL(18,4)) AS FREIGHT
  FROM ASG_CLEAN.FACTRESELLERSALES_CLEAN f
),
unioned AS (
  SELECT * FROM internet
  UNION ALL
  SELECT * FROM reseller
)
SELECT
  SALES_CHANNEL,
  SALES_ORDER_NUMBER,
  SALES_ORDER_LINE_NUMBER,
  PRODUCT_KEY,
  CUSTOMER_KEY,
  RESELLER_KEY,
  SALES_TERRITORY_KEY,
  ORDER_DATE,
  DUE_DATE,
  SHIP_DATE,
  ORDER_QTY,
  SALES_AMOUNT,
  TOTAL_PRODUCT_COST,
  FREIGHT,
  DATEDIFF('day', ORDER_DATE, SHIP_DATE) AS DAYS_TO_SHIP,
  DATEDIFF('day', ORDER_DATE, DUE_DATE) AS DAYS_ORDER_TO_DUE,
  CASE
    WHEN SHIP_DATE IS NULL OR DUE_DATE IS NULL THEN NULL
    WHEN SHIP_DATE <= DUE_DATE THEN 1
    ELSE 0
  END AS ON_TIME_FLAG,
  CASE
    WHEN SHIP_DATE IS NULL OR DUE_DATE IS NULL THEN NULL
    ELSE GREATEST(DATEDIFF('day', DUE_DATE, SHIP_DATE), 0)
  END AS DAYS_LATE
FROM unioned;

-- 3) Monthly shipping performance by channel, territory, and product category
CREATE OR REPLACE TABLE ASG_MART.SUPPLYCHAIN_SHIPPING_MONTHLY AS
SELECT
  DATE_TRUNC('month', o.ORDER_DATE) AS ORDER_MONTH,
  o.SALES_CHANNEL,
  t.SALESTERRITORYREGION AS SALES_TERRITORY_REGION,
  t.SALESTERRITORYCOUNTRY AS SALES_TERRITORY_COUNTRY,
  t.SALESTERRITORYGROUP AS SALES_TERRITORY_GROUP,
  p.PRODUCT_CATEGORY,
  p.PRODUCT_SUBCATEGORY,
  COUNT(DISTINCT o.SALES_ORDER_NUMBER) AS ORDER_COUNT,
  SUM(o.ORDER_QTY) AS TOTAL_ORDER_QTY,
  SUM(o.SALES_AMOUNT) AS TOTAL_SALES_AMOUNT,
  AVG(o.DAYS_TO_SHIP) AS AVG_DAYS_TO_SHIP,
  AVG(o.DAYS_LATE) AS AVG_DAYS_LATE,
  AVG(o.ON_TIME_FLAG) AS ON_TIME_RATE,
  SUM(o.FREIGHT) AS TOTAL_FREIGHT
FROM ASG_MART.SUPPLYCHAIN_ORDER_LINE o
LEFT JOIN ASG_CLEAN.DIMSALESTERRITORY_CLEAN t
  ON o.SALES_TERRITORY_KEY = t.SALESTERRITORYKEY
LEFT JOIN ASG_MART.INVENTORY_PRODUCT_PROFILE p
  ON o.PRODUCT_KEY = p.PRODUCT_KEY
WHERE o.ORDER_DATE IS NOT NULL
GROUP BY
  DATE_TRUNC('month', o.ORDER_DATE),
  o.SALES_CHANNEL,
  t.SALESTERRITORYREGION,
  t.SALESTERRITORYCOUNTRY,
  t.SALESTERRITORYGROUP,
  p.PRODUCT_CATEGORY,
  p.PRODUCT_SUBCATEGORY;

-- 4) Monthly demand (inventory consumption) by product and channel
CREATE OR REPLACE TABLE ASG_MART.INVENTORY_DEMAND_MONTHLY AS
SELECT
  DATE_TRUNC('month', o.ORDER_DATE) AS ORDER_MONTH,
  o.SALES_CHANNEL,
  o.PRODUCT_KEY,
  p.PRODUCT_NAME,
  p.PRODUCT_CATEGORY,
  p.PRODUCT_SUBCATEGORY,
  COUNT(DISTINCT o.SALES_ORDER_NUMBER) AS ORDER_COUNT,
  SUM(o.ORDER_QTY) AS TOTAL_ORDER_QTY,
  SUM(o.SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM ASG_MART.SUPPLYCHAIN_ORDER_LINE o
LEFT JOIN ASG_MART.INVENTORY_PRODUCT_PROFILE p
  ON o.PRODUCT_KEY = p.PRODUCT_KEY
WHERE o.ORDER_DATE IS NOT NULL
GROUP BY
  DATE_TRUNC('month', o.ORDER_DATE),
  o.SALES_CHANNEL,
  o.PRODUCT_KEY,
  p.PRODUCT_NAME,
  p.PRODUCT_CATEGORY,
  p.PRODUCT_SUBCATEGORY;

-- 5) Reorder risk proxy using sales velocity vs. stock policy
CREATE OR REPLACE TABLE ASG_MART.INVENTORY_REORDER_RISK AS
WITH demand AS (
  SELECT
    PRODUCT_KEY,
    MIN(ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(ORDER_DATE) AS LAST_ORDER_DATE,
    SUM(ORDER_QTY) AS TOTAL_ORDER_QTY,
    DATEDIFF('day', MIN(ORDER_DATE), MAX(ORDER_DATE)) + 1 AS ACTIVE_DAYS
  FROM ASG_MART.SUPPLYCHAIN_ORDER_LINE
  WHERE ORDER_DATE IS NOT NULL
  GROUP BY PRODUCT_KEY
),
calc AS (
  SELECT
    PRODUCT_KEY,
    FIRST_ORDER_DATE,
    LAST_ORDER_DATE,
    TOTAL_ORDER_QTY,
    ACTIVE_DAYS,
    TOTAL_ORDER_QTY / NULLIF(ACTIVE_DAYS, 0) AS AVG_DAILY_DEMAND
  FROM demand
)
SELECT
  p.PRODUCT_KEY,
  p.PRODUCT_NAME,
  p.PRODUCT_CATEGORY,
  p.PRODUCT_SUBCATEGORY,
  p.SAFETY_STOCK_LEVEL,
  p.REORDER_POINT,
  p.DAYS_TO_MANUFACTURE,
  c.FIRST_ORDER_DATE,
  c.LAST_ORDER_DATE,
  c.TOTAL_ORDER_QTY,
  c.ACTIVE_DAYS,
  c.AVG_DAILY_DEMAND,
  p.SAFETY_STOCK_LEVEL / NULLIF(c.AVG_DAILY_DEMAND, 0) AS SAFETY_STOCK_DAYS_COVER,
  p.REORDER_POINT / NULLIF(c.AVG_DAILY_DEMAND, 0) AS REORDER_POINT_DAYS_COVER,
  CASE
    WHEN c.AVG_DAILY_DEMAND IS NULL THEN 'No Demand'
    WHEN p.REORDER_POINT IS NULL THEN 'Unknown'
    WHEN (p.REORDER_POINT / NULLIF(c.AVG_DAILY_DEMAND, 0)) < p.DAYS_TO_MANUFACTURE THEN 'High Risk'
    WHEN (p.REORDER_POINT / NULLIF(c.AVG_DAILY_DEMAND, 0)) < p.DAYS_TO_MANUFACTURE * 1.5 THEN 'Medium Risk'
    ELSE 'Low Risk'
  END AS REORDER_RISK_LEVEL
FROM ASG_MART.INVENTORY_PRODUCT_PROFILE p
LEFT JOIN calc c
  ON p.PRODUCT_KEY = c.PRODUCT_KEY;
