USE ROLE TRAINING_ROLE;
USE WAREHOUSE CATFISH_WH;
USE DATABASE GRP1_ASG;

CREATE SCHEMA IF NOT EXISTS ASG_TRANSFORMATIONS;
USE SCHEMA ASG_TRANSFORMATIONS;

-- For Power BI
CREATE SCHEMA IF NOT EXISTS ASG_MART;



-- 1) DIMENSION VIEWS (minimal columns only)
CREATE OR REPLACE VIEW V_DIM_SALES_TERRITORY AS
SELECT
  SALESTERRITORYKEY            AS SALESTERRITORYKEY,
  TRIM(SALESTERRITORYREGION)   AS SALESTERRITORYREGION,
  TRIM(SALESTERRITORYCOUNTRY)  AS SALESTERRITORYCOUNTRY,
  TRIM(SALESTERRITORYGROUP)    AS SALESTERRITORYGROUP
FROM ASG_CLEAN.DIMSALESTERRITORY_CLEAN
WHERE SALESTERRITORYKEY IS NOT NULL;


CREATE OR REPLACE VIEW V_DIM_DATE AS
SELECT
  DATEKEY                     AS DATEKEY,
  FULLDATEALTERNATEKEY        AS FULLDATE,
  CALENDARYEAR                AS CALENDARYEAR,
  CALENDARQUARTER             AS CALENDARQUARTER,
  MONTHNUMBEROFYEAR           AS MONTHNUMBEROFYEAR,
  TRIM(ENGLISHMONTHNAME)      AS ENGLISHMONTHNAME,
  DAYNUMBEROFMONTH            AS DAYNUMBEROFMONTH,
  DAYNUMBEROFWEEK             AS DAYNUMBEROFWEEK,
  TRIM(ENGLISHDAYNAMEOFWEEK)  AS ENGLISHDAYNAMEOFWEEK
FROM ASG_CLEAN.DIMDATE_CLEAN
WHERE DATEKEY IS NOT NULL;


CREATE OR REPLACE VIEW V_DIM_CUSTOMER AS
SELECT
  CUSTOMERKEY   AS CUSTOMERKEY,
  GEOGRAPHYKEY  AS GEOGRAPHYKEY
FROM ASG_CLEAN.DIMCUSTOMER_CLEAN
WHERE CUSTOMERKEY IS NOT NULL;


CREATE OR REPLACE VIEW V_DIM_GEOGRAPHY AS
SELECT
  GEOGRAPHYKEY                    AS GEOGRAPHYKEY,
  TRIM(CITY)                      AS CITY,
  TRIM(STATEPROVINCENAME)         AS STATEPROVINCENAME,
  TRIM(ENGLISHCOUNTRYREGIONNAME)  AS ENGLISHCOUNTRYREGIONNAME,
  TRIM(POSTALCODE)                AS POSTALCODE,
  SALESTERRITORYKEY               AS GEO_SALESTERRITORYKEY
FROM ASG_CLEAN.DIMGEOGRAPHY_CLEAN
WHERE GEOGRAPHYKEY IS NOT NULL;


-- 2) FACT VIEW (Internet Sales only, minimal + needed for profit)

CREATE OR REPLACE VIEW V_FACT_INTERNET_SALES AS
SELECT
  SALESORDERNUMBER        AS SALESORDERNUMBER,
  SALESORDERLINENUMBER    AS SALESORDERLINENUMBER,

  ORDERDATE               AS ORDERDATE,
  CUSTOMERKEY             AS CUSTOMERKEY,
  SALESTERRITORYKEY       AS SALESTERRITORYKEY,

  ORDERQUANTITY           AS ORDERQUANTITY,

  CAST(SALESAMOUNT       AS DECIMAL(18,4)) AS SALESAMOUNT,
  CAST(DISCOUNTAMOUNT    AS DECIMAL(18,4)) AS DISCOUNTAMOUNT,
  CAST(TOTALPRODUCTCOST  AS DECIMAL(18,4)) AS TOTALPRODUCTCOST,
  CAST(TAXAMOUNT         AS DECIMAL(18,4)) AS TAXAMOUNT,
  CAST(FREIGHT           AS DECIMAL(18,4)) AS FREIGHT

FROM ASG_CLEAN.FACTINTERNETSALES_CLEAN
WHERE SALESTERRITORYKEY IS NOT NULL
  AND ORDERDATE IS NOT NULL;


-- 3) SALES TERRITORY DETAIL VIEW (joins + features)
CREATE OR REPLACE VIEW V_SALES_TERRITORY_DETAIL AS
SELECT
  'Internet' AS SALESCHANNEL,

  f.SALESORDERNUMBER,
  f.SALESORDERLINENUMBER,
  f.ORDERDATE,

  d.CALENDARYEAR,
  d.CALENDARQUARTER,
  d.MONTHNUMBEROFYEAR,
  d.ENGLISHMONTHNAME,
  TO_VARCHAR(f.ORDERDATE, 'YYYY-MM') AS YEARMONTH,

  f.SALESTERRITORYKEY,
  t.SALESTERRITORYREGION,
  t.SALESTERRITORYCOUNTRY,
  t.SALESTERRITORYGROUP,

  f.CUSTOMERKEY,
  c.GEOGRAPHYKEY,
  g.CITY,
  g.STATEPROVINCENAME,
  g.ENGLISHCOUNTRYREGIONNAME,
  g.POSTALCODE,

  f.ORDERQUANTITY,
  f.SALESAMOUNT,
  f.DISCOUNTAMOUNT,
  f.TOTALPRODUCTCOST,
  f.TAXAMOUNT,
  f.FREIGHT,

  -- Features 
  (f.SALESAMOUNT - f.TOTALPRODUCTCOST) AS GROSSPROFIT,
  IFF(f.SALESAMOUNT = 0, NULL,
      (f.SALESAMOUNT - f.TOTALPRODUCTCOST) / f.SALESAMOUNT) AS GROSSMARGINPCT,

  -- Net profit after tax + freight (good for dashboard)
  (f.SALESAMOUNT - f.TOTALPRODUCTCOST - f.TAXAMOUNT - f.FREIGHT) AS NETPROFIT,
  IFF(f.SALESAMOUNT = 0, NULL, f.FREIGHT / f.SALESAMOUNT) AS FREIGHTPCTOFSALES,
  IFF(f.SALESAMOUNT = 0, NULL, f.TAXAMOUNT / f.SALESAMOUNT) AS TAXPCTOFSALES

FROM V_FACT_INTERNET_SALES f
JOIN V_DIM_DATE d
  ON d.FULLDATE = f.ORDERDATE
JOIN V_DIM_SALES_TERRITORY t
  ON t.SALESTERRITORYKEY = f.SALESTERRITORYKEY
LEFT JOIN V_DIM_CUSTOMER c
  ON c.CUSTOMERKEY = f.CUSTOMERKEY
LEFT JOIN V_DIM_GEOGRAPHY g
  ON g.GEOGRAPHYKEY = c.GEOGRAPHYKEY;


-- 4) MONTHLY MART TABLE (used for Power BI)
CREATE OR REPLACE TABLE ASG_MART.SALES_TERRITORY_MONTHLY AS
SELECT
  YEARMONTH,
  CALENDARYEAR,
  MONTHNUMBEROFYEAR,
  ENGLISHMONTHNAME,

  SALESTERRITORYGROUP,
  SALESTERRITORYCOUNTRY,
  SALESTERRITORYREGION,

  COUNT(DISTINCT SALESORDERNUMBER) AS ORDERS,
  SUM(ORDERQUANTITY)               AS UNITS,

  SUM(SALESAMOUNT)                 AS REVENUE,
  SUM(TOTALPRODUCTCOST)            AS COST,
  SUM(GROSSPROFIT)                 AS GROSSPROFIT,
  AVG(GROSSMARGINPCT)              AS AVGGROSSMARGINPCT,

  SUM(TAXAMOUNT)                   AS TOTALTAX,
  SUM(FREIGHT)                     AS TOTALFREIGHT,
  SUM(NETPROFIT)                   AS NETPROFIT,
  AVG(FREIGHTPCTOFSALES)           AS AVGFREIGHTPCTOFSALES,
  AVG(TAXPCTOFSALES)               AS AVGTAXPCTOFSALES

FROM ASG_TRANSFORMATIONS.V_SALES_TERRITORY_DETAIL
GROUP BY
  YEARMONTH, CALENDARYEAR, MONTHNUMBEROFYEAR, ENGLISHMONTHNAME,
  SALESTERRITORYGROUP, SALESTERRITORYCOUNTRY, SALESTERRITORYREGION;


-- 5) VALIDATION CHECKS
 

-- Ensure terroritory keys are NOT NULL
SELECT COUNT(*) AS NULL_TERRITORYKEY
FROM ASG_CLEAN.FACTINTERNETSALES_CLEAN
WHERE SALESTERRITORYKEY IS NULL; -- Verified, count at 0


-- Ensures referential integrity between fact and dimension tables
SELECT COUNT(*) AS ORPHAN_TERRITORY_KEYS
FROM ASG_CLEAN.FACTINTERNETSALES_CLEAN f
LEFT JOIN ASG_CLEAN.DIMSALESTERRITORY_CLEAN t
  ON f.SALESTERRITORYKEY = t.SALESTERRITORYKEY
WHERE f.SALESTERRITORYKEY IS NOT NULL
  AND t.SALESTERRITORYKEY IS NULL; -- Verified, count at 0

-- Show sales records linked to customers that do not exist in the Customer dimension
SELECT COUNT(*) AS ORPHAN_CUSTOMER_KEYS
FROM ASG_CLEAN.FACTINTERNETSALES_CLEAN f
LEFT JOIN ASG_CLEAN.DIMCUSTOMER_CLEAN c
  ON f.CUSTOMERKEY = c.CUSTOMERKEY
WHERE f.CUSTOMERKEY IS NOT NULL
  AND c.CUSTOMERKEY IS NULL; -- Verified, count at 0

-- Ensure geographic fields are available
SELECT COUNT(*) AS ORPHAN_GEOGRAPHY_KEYS
FROM ASG_CLEAN.DIMCUSTOMER_CLEAN c
LEFT JOIN ASG_CLEAN.DIMGEOGRAPHY_CLEAN g
  ON c.GEOGRAPHYKEY = g.GEOGRAPHYKEY
WHERE c.GEOGRAPHYKEY IS NOT NULL
  AND g.GEOGRAPHYKEY IS NULL; -- Verified, count at 0

-- Ensure no duplicate or drop in sales records for Fact + Dimension views
SELECT COUNT(*) AS FACT_ROWS
FROM ASG_TRANSFORMATIONS.V_FACT_INTERNET_SALES;

SELECT COUNT(*) AS DETAIL_ROWS
FROM ASG_TRANSFORMATIONS.V_SALES_TERRITORY_DETAIL; -- Verified, both counts at 60398

